name: Upload Project
on:
  push:
    tags:
        - v* # Only build if there is a version tag.
env:
  BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }} #API Key
  ITCH_GAME: liquid-kitty #Change base on game name on itch
  ITCH_USER: supriseorb
  Version: 0


jobs:
  UploadArtifact: #Manually build then use this job to upload builds as artifacts
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p Build
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: Build
      
  deployToItch:
    name: Deploy game to itch.io
    runs-on: ubuntu-latest
    needs: [UploadArtifact]
    steps:
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: Build
    - uses: josephbmanley/butler-publish-itchio-action@master
      env:
        CHANNEL: windows-x64
        PACKAGE: Build/LiquidKittyWindows64
    - uses: josephbmanley/butler-publish-itchio-action@master
      env:
        CHANNEL: web
        PACKAGE: Build/LiquidKittyWebGL
    # Delete the artifact after we upload it to itch.io
    - uses: geekyeggo/delete-artifact@v1
      with:
        name: Build